version: "3"

services:
  db:
    image: postgres:12.5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=learning_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
